name: CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/resume-video-creator:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/resume-video-creator:${{ github.ref_name }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/resume-video-creator:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/resume-video-creator:buildcache,mode=max

    - name: Deploy to production
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Deploying version ${{ github.ref_name }} to production"
        # Add your deployment commands here 